### ISSUE TITLE
Issue with basecalled fast5 from master of pores pipeline 

### ISSUE THREAD

**Issue by callumparr** [adnaniazi/tailfindr#10]
https://github.com/biocorecrg/master_of_pores/issues/58#issue-607055852 

I have some fast5 that were originally outputted to pass and fail with MinKNOW livebasecalling. I am unsure if squiggles/events were written on the fast5 or the fast5 were just moves to pass or fail directories. 

<img width="851" alt="Screen Shot 2020-04-26 at 5 39 31 PM" src="https://user-images.githubusercontent.com/41637575/80313818-50bc4e00-87e5-11ea-8da3-f44c9a28d22f.png">

I rebasecalled the fast5 files through master of pores NanoPreprocess which runs smoothly. 

I am unsure what the basecall group should be as master of pores should overwrite previous squiggles? 

`
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[d7/f72177] process > tailfindr                  [  0%] 0 of 574
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[ec/9055b7] process > tailfindr                  [  0%] 1 of 574, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[ec/9055b7] process > tailfindr                  [  0%] 1 of 574, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[d7/f72177] process > tailfindr                  [  0%] 1 of 573, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
WARN: Killing pending tasks (1)
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
  ────────────────────────────────────────────────────────────────────────────────
  ☰ You have configured tailfindr as following:
  ❯ fast5_dir:         ./
  ❯ save_dir:          ./
  ❯ csv_filename:      Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv
  ❯ num_cores:         4
  ❯ basecall_group:    Basecall_1D_000
  ❯ save_plots:        FALSE
  ❯ plot_debug_traces: FALSE
  ❯ plotting_library:  rbokeh
  ── Processing started at 2020-04-27 01:31:47 ───────────────────────────────────
  ● Searching for all Fast5 files...
    Done! Found 1 Fast5 files.
  ● Analyzing a single Fast5 file to assess if your data 
    is in an acceptable format...
    ✖ Fatal error! Your data has been basecalled with MinKNOW
      live basecalling which currently does not save the
      Events/Move table in the Analyses/Basecall_1D_000 section of
      the FAST5 file. You should rebasecall your FAST5 files using 
      standalone Guppy or Albacore, and then use tailfindr on the 
      rebasecalled files. Please adjust the value of basecall_group
      parameter in such a case, so that tailfindr can find the 
      Events/Move table in the specified basecall_group. You can
      check which basecall_group the Event/Move is residing by
      opening your FAST5 file in HDFView.
  
      If the Events/Move is present in the data and you have
      specified the correct basecall_group, but you still
      get this error then please open an issue on GitHub:
      https://github.com/adnaniazi/tailfindr/issues
      Remember to attach a few (around 5) of your FAST5 files
      to help us understand the issue.
  ── Processing ended at 2020-04-27 01:32:18 ─────────────────────────────────────
  ✖ tailfindr finished unsuccessfully!
  [1] 0

Work dir:
  /home/callum/master_of_pores/NanoTail/work/ec/9055b7a0d633713ec307041462096f

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanotail.nf' at line: 303 or see '.nextflow.log' file for more details
`

**Comment by NuriaDiaz** [comment]
Hey! How did  you solve this issue? I have the exact same problem. I also re-basecalled using Master of Pores and Guppy and also run smoothly.

executor >  local (17)
[-        ] process > check_reference                [  0%] 0 of 1
[e2/ddd28c] process > tailfindr (preprocess_outpu... [  0%] 0 of 50
[d8/37a548] process > filter_bam (preprocess_outp... [  0%] 0 of 1
[-        ] process > tail_nanopolish                -
[-        ] process > collect_nanopolish_results     -
[-        ] process > collect_tailfindr_results      -
[-        ] process > join_results                   -
Skipping the email
Error executing process > 'tailfindr (preprocess_output_wt-ADG237_pass_18f3214b_6)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (preprocess_output_wt-ADG237_pass_18f3214b_6)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'preprocess_output_wt-ADG237_pass_18f3214b_6_findr.csv', num_cores = 8)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
  ────────────────────────────────────────────────────────────────────────────────
  ☰ You have configured tailfindr as following:
  ❯ fast5_dir:         ./
  ❯ save_dir:          ./
  ❯ csv_filename:      preprocess_output_wt-ADG237_pass_18f3214b_6_findr.csv
  ❯ num_cores:         8
  ❯ basecall_group:    Basecall_1D_000
  ❯ save_plots:        FALSE
  ❯ plot_debug_traces: FALSE
  ❯ plotting_library:  rbokeh
  ── Processing started at 2020-10-01 12:16:13 ───────────────────────────────────
  ● Searching for all Fast5 files...
    Done! Found 1 Fast5 files.
  ● Analyzing a single Fast5 file to assess if your data 
    is in an acceptable format...
    ✖ Fatal error! Your data has been basecalled with MinKNOW
      live basecalling which currently does not save the
      Events/Move table in the Analyses/Basecall_1D_000 section of
      the FAST5 file. You should rebasecall your FAST5 files using 
      standalone Guppy or Albacore, and then use tailfindr on the 
      rebasecalled files. Please adjust the value of basecall_group
      parameter in such a case, so that tailfindr can find the 
      Events/Move table in the specified basecall_group. You can
      check which basecall_group the Event/Move is residing by
      opening your FAST5 file in HDFView.
  
      If the Events/Move is present in the data and you have
      specified the correct basecall_group, but you still
      get this error then please open an issue on GitHub:
      https://github.com/adnaniazi/tailfindr/issues
      Remember to attach a few (around 5) of your FAST5 files
executor >  local (17)
[-        ] process > check_reference                [  0%] 0 of 1
[e2/ddd28c] process > tailfindr (preprocess_outpu... [  3%] 1 of 35, failed: 1
[-        ] process > filter_bam (preprocess_outp... -
[-        ] process > tail_nanopolish                -
[-        ] process > collect_nanopolish_results     -
[-        ] process > collect_tailfindr_results      -
[-        ] process > join_results                   -
Skipping the email
Error executing process > 'tailfindr (preprocess_output_wt-ADG237_pass_18f3214b_6)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (preprocess_output_wt-ADG237_pass_18f3214b_6)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'preprocess_output_wt-ADG237_pass_18f3214b_6_findr.csv', num_cores = 8)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
  ────────────────────────────────────────────────────────────────────────────────
  ☰ You have configured tailfindr as following:
  ❯ fast5_dir:         ./
  ❯ save_dir:          ./
  ❯ csv_filename:      preprocess_output_wt-ADG237_pass_18f3214b_6_findr.csv
  ❯ num_cores:         8
  ❯ basecall_group:    Basecall_1D_000
  ❯ save_plots:        FALSE
  ❯ plot_debug_traces: FALSE
  ❯ plotting_library:  rbokeh
  ── Processing started at 2020-10-01 12:16:13 ───────────────────────────────────
  ● Searching for all Fast5 files...
    Done! Found 1 Fast5 files.
  ● Analyzing a single Fast5 file to assess if your data 
    is in an acceptable format...
    ✖ Fatal error! Your data has been basecalled with MinKNOW
      live basecalling which currently does not save the
      Events/Move table in the Analyses/Basecall_1D_000 section of
      the FAST5 file. You should rebasecall your FAST5 files using 
      standalone Guppy or Albacore, and then use tailfindr on the 
      rebasecalled files. Please adjust the value of basecall_group
      parameter in such a case, so that tailfindr can find the 
      Events/Move table in the specified basecall_group. You can
      check which basecall_group the Event/Move is residing by
      opening your FAST5 file in HDFView.
  
      If the Events/Move is present in the data and you have
      specified the correct basecall_group, but you still
      get this error then please open an issue on GitHub:
      https://github.com/adnaniazi/tailfindr/issues
      Remember to attach a few (around 5) of your FAST5 files
      to help us understand the issue.
  ── Processing ended at 2020-10-01 12:16:15 ─────────────────────────────────────
  ✖ tailfindr finished unsuccessfully!
  [1] 0

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Work dir:
  /media/data/nuria/nanopore/Fabian/bcn_pipeline/preprocess_output_wt/fast5_files/work/6b/a11a81ae306a67fe54388ec2cef64b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


Thanks a lot in advance!
Núria

**Comment by adnaniazi** [comment]
Hi Nuria,

Thanks for using tailfindr.

Can you please try to install the ont-vbz-hdf-plugin for your operating system from this link: https://github.com/nanoporetech/vbz_compression/releases/tag/v1.0.1

After installation, try to run your script again. If it still does not work, then please email me (adnaniazi@gmail.com) one of your Fast5 files. I will have a look at it. Thanks.

Adnan

**Comment by NuriaDiaz** [comment]
Hi Adnan,

Thanks a lot for your super fast reply. Where should I exactly store this plugin? As I mentioned, I'm using the Master Of Pores pipeline, so the Tailfindr script/programs is inside it.

Best,
Núria

**Comment by adnaniazi** [comment]
These are executable installers so you should follow the instructions for your operating system on how to install it. For example for Mac you just need to download the Mac specific package and install it by clicking it and pressing next next next. For linux, you should follow the instructions on how to install a .deb package in Linux operating system.

**Comment by lucacozzuto** [comment]
Dear all, we just released Master of Pores 2 where we give support to the compressed files. So now you can use tailfindr from mop_tail on those files. 
PS: many thanks to the developers of tailfindr for their tool!

https://github.com/biocorecrg/MOP2
