### ISSUE TITLE
Empty html plots

### ISSUE THREAD

**Issue by MustafaElshani** [adnaniazi/tailfindr#15]
Hi 

The code runs well with no errors I do generate htmls however they are empty when opened in a browser, but they are up to 20Mb. Any special plugins required ?

Mustafa

**Comment by adnaniazi** [comment]
Hi Mustafa,

Can you send a few files to me. You can email them to me on adnaniazi@gmail.com. I will check them out.

**Comment by adnaniazi** [comment]
Hi Mustafa,

Thank you for sending me the files. When you open the html file in a webbrowser, the html file loads a .css and .js file; these are downloaded automatically from the web. These two files help render the html file correctly. It seems like there is a bug in the latest version of .css and .js files that are downloaded by current version of rbokeh. I cannot solve it as it from the developers of rbokeh. But I can show you a way of how to repair the html files you have, so that they render correctly. Follow this procedure for each of your html files:

1. Open in some text editor and search for following two lines (lines 4 - 5):
<script src='https://cdn.pydata.org/bokeh/release/bokeh-0.12.5.min.js'></script>
<link href='https://cdn.pydata.org/bokeh/release/bokeh-0.12.5.min.css' rel='stylesheet'>

2. Replace them with:
<link rel="stylesheet" href="http://cdn.bokeh.org/bokeh/release/bokeh-0.12.3.min.css" type="text/css" />
<script type="text/javascript" src="http://cdn.bokeh.org/bokeh/release/bokeh-0.12.3.min.js"></script>

3. Save the file again with these changes.

4. Load the html file again in the webbrowser. It should load correctly now.

You can just write a simple script that can replace the two lines for all your html files, and then all of them will render correctly.

Hope this helps. I am attaching a screenshot of one of your reads which rendered correctly after I made these changes.

Best,
Adnan
<img width="1005" alt="Screenshot 2020-08-14 at 04 53 59" src="https://user-images.githubusercontent.com/6848063/90208869-2faa5800-ddea-11ea-97fd-acb8f215bd45.png">

**Comment by MustafaElshani** [comment]
Thank You Adnan 

That works perfectly, I had to go through and change all plots so used the following code until there is a permanent fix from rbokeh

`cd /path/to/plots
sed -i "s#<script src='https://cdn.pydata.org/bokeh/release/bokeh-0.12.5.min.js'></script>"#'<script type="text/javascript" src="http://cdn.bokeh.org/bokeh/release/bokeh-0.12.3.min.js"></script>#g' *html`

Kind Regards 

Mustafa

**Comment by adnaniazi** [comment]
Great! Glad that it worked.

Adnan

**Comment by nemitheasura** [comment]
Dear @MustafaElshani and @adnaniazi , 

in my case your code was insufficient, as the interactive buttons glitched with the squiggles. I replaced both lines, as Adnan suggested with following sed:

`
![image](https://user-images.githubusercontent.com/68285258/99731198-d83d1780-2abd-11eb-85f9-75f7884a592f.png)

`

And now everything looks way better, all of the squiggles look neat. 

Best,
Nemi

**Comment by manburst** [comment]
Hello sir, I have tried to edit the code in HTML file as you described above.
It works but not perfectly, some results still not showing.
Here is HTML plot screenshot, above the move is not showing
![image](https://user-images.githubusercontent.com/68594551/106285414-076ac480-6277-11eb-8f69-286f3c98706a.png)

**Comment by manburst** [comment]
Dear @nemitheasura  @MustafaElshani 
Could you specific more where to put the code. I have no idea where is  `cd /path/to/plots` of rbokeh.
Thanks

**Comment by manburst** [comment]
@adnaniazi 
Sir, I tried to edit the code as you described above. However, the result came out not so perfectly. the poly-A graph is not shown and I also cannot interact with the graph.
Here is the screenshot
![image](https://user-images.githubusercontent.com/68594551/106290805-74815880-627d-11eb-81c5-4cad3aeb6543.png)
I have tried to fix it with scripts like @MustafaElshani and @nemitheasura but I have no idea where is `cd /path/to/plots` of rbokeh, so where to put the script in.
Thanks

**Comment by adnaniazi** [comment]
@manburst Can please try the solution mentioned [here](https://github.com/adnaniazi/tailfindr/issues/15#issuecomment-673855365) word-for-word. It says that you have to open the HTML file in some kind of a text editor, and search for two particular lines, and then replace them with another two lines.

**Comment by manburst** [comment]
@adnaniazi Yes, I have replaced them already but somehow the result comes out as https://github.com/adnaniazi/tailfindr/issues/15#issuecomment-769857925

**Comment by adnaniazi** [comment]
@manburst Can you start over again and do the replacement manually after generating fresh HTML file form tailfindr. You have to be carefully that you do not make any mistakes in writing the two new lines.

**Comment by manburst** [comment]
Thanks, it works now.
