### ISSUE TITLE
NAs in polyA tail length estimation

### ISSUE THREAD

**Issue by ahorvath** [adnaniazi/tailfindr#16]
Dear @adnaniazi,

What do **NA**s most likely represent in the polyA tail estimation? Can we speculate that they are typically longer or sorter than the population? 

Thanks for developing this great package.

Best,
Attila

**Comment by adnaniazi** [comment]
Dear Attila,

Thanks for using tailfindr. 

NAs in tail length estimation in majority of cases means that there was no polyA-tail-like region found in the squiggle in the beginning for the RNA read. Wrong segmentation from MinION can sometimes generate such kinds of reads. In minority of cases, NAs might also be due to failure of tailfindr algorithm itself, but those are very rare; majority of NAs come from there not being a polyA like region in the raw Nanopore signal.

Hope this helps!

Best,
Adnan

**Comment by ahorvath** [comment]
Sounds great. Actually, this would make much sense biologically in some of our conditions (transcripts having no polyA tail).

Thanks for your prompt and professional answer!
