### ISSUE TITLE
Cannot find the correct polyA tail for RNA reads basecalled with Guppy 4.2.2

### ISSUE THREAD

**Issue by thupchnsky** [adnaniazi/tailfindr#18]
Dear developers,

I find that the results returned by tailfindr method in master branch cannot correctly recognize the polyA tail region in my reads. The fast5 file contains several RNA reads basecalled with Guppy 4.2.2. Each read has its own fastq and move table, which is stored in group read_id/analyses/Basecall_1D_001. I am following the instruction to change the basecall group, so I use command:

`df <- find_tails(fast5_dir = './RNA_reads', save_dir = '~/Downloads', csv_filename = 'rna_tails.csv', num_cores = 5, basecall_group = 'Basecall_1D_001', save_plots = TRUE, plotting_library = 'rbokeh')`

And when I look into the results, some pretty obvious polyA tail are not found. One example is shown here:
![image](https://user-images.githubusercontent.com/50838819/103042979-f8d71200-4540-11eb-96cf-7c5e5ec81361.png)

Instead it finds some regions like this, which I dont think is a polyA tail, in another read:
![image](https://user-images.githubusercontent.com/50838819/103042785-54ed6680-4540-11eb-9dcb-39fa7ce677d2.png)

Moreover some of the reads cannot be processed. Their read ids are missing (there should be 10 reads in total)
![image](https://user-images.githubusercontent.com/50838819/103043142-74d15a00-4541-11eb-9eb5-89a69beb72fa.png)

I am not sure this is caused by the data itself, or I am not using the method correctly. I have sent the data to your email for your testing. And I really appreciate your help on this! Thanks in advance.

P.S. I also find the warning appeared in some previous post about using unnest:
`cols` is now required when using unnest().
Please use `cols = c(read_id, tail_start, tail_end, samples_per_nt, tail_length, polya_fastq, file_path)`

**Comment by adnaniazi** [comment]
Dear Chao Pan,

Thank you for trying out tailfindr.

I will try to address the issues you pointed out one by one.

**Case 1 where the polyA tail is at the end:** RNA sequencing happens 3' to 5' which means that when you plot the signal for a transcript, then polyA tail would be on the left and not on the right. tailfindr expects -- from empirical evidence -- the polyA tail to be present in the first 3000 samples to the left. Your erroneous read seems like it was segmented wrongly by MinKNOW, where it includes part one transcript in the beginning, and a polyA tail from the next transcript at the end (both fused together). Since there is no polyA tail in the correct location (i.e., the first 3000 current samples), therefore, tailfindr didn't find any polyA tail and outputted NA. 

**Case 2 PolyA tail found in the wrong region:** Yes, in this case tailfindr is wrong. But it is because the read is weird. If you look at its FastA, it is entirely GC rich. This unusual read pattern throws the tailfindr algorithm off.
UCAACGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC

** Case 3 No read id ** These reads are fatal reads. They crashed the tailfindr algorithm. I would recommend that you just run nanopolish polyA on your reads to see if it fairs any better because it uses a different approach to call polyA tails. I would guess the performance would be the same because there is something weird going on your data as evident from case 1 and case 2.

** Warning ** Those are related to older R syntax. These warnings have no effect on the output. You can safely ignore them.

Happy holidays.

Best,
Adnan

**Comment by thupchnsky** [comment]
Thanks for the replies, Adnan! Just want to check for the first case would it make sense then I do one round of tail finding using the original reads, then do another round of tail finding using the reversed reads, where all data including fastq, move table and raw signal are reversed? I just looked up some other reads and it seems that it lies either in pretty left or pretty right locations, so just want to check if using the algorithm on the reversed data is a possible solution here?

Thanks!

**Comment by adnaniazi** [comment]
No, I don't think this approach would work very well. This is because in good RNA reads you have first the signal for the adapter, then the polyA tail signal, and then the signal for the transcript. 
**adapter signal --> polyA tail signal --> transcript signal**
tailfindr uses the signature adapter signal to define the start of the polyA tail and then finds the end of the polyA tail by searching for the start of the transcript signal.

Now in case of fused reads, as in case 1, you have:
**transcript signal of first transcript -> adapter signal of second transcript-> polyA tail signal of second transcript -> transcript signal of second transcript**

If you reverse the read, then you would get:
**transcript signal of second transcript ->  polyA tail signal of the second transcript  -> adapter signal of the second transcript -> transcript signal of first transcript** 

This does not follow the order of things (**adapter --> polyA tail --> transcript**) that tailfindr expects because the polyA tail is coming after the adapter signal. 

You should search for a tool that can correct the segmentation fault by splitting the fused read into two separate reads. May be then tailfindr would work.

But this would be a lot of work. I would recommend that you just try to figure out why you have such abnormally segmented (or fused) reads in the first place, and, as to why you have such GC-rich reads? tailfindr cannot not work with these reads because it is not designed for such artificial sequences. 

Best,
Adnan

**Comment by thupchnsky** [comment]
Sure. I will look into this. Many thanks!
