### ISSUE TITLE
Error in f5_obj$ls

### ISSUE THREAD

**Issue by MustafaElshani** [adnaniazi/tailfindr#34]
Hi 

After running the following on a new linux build 
```
df <- find_tails(fast5_dir = "OCIAML3_sup_basecalled/workspace/",
                 save_dir = 'analysis/tailfindr',
                 basecall_group = 'Basecall_1D_001',
                 csv_filename = 'cdna_tails.csv',
                 num_cores = 40)
```

I get the following error

This happens after the Discovering reads in the multifast5 files

```
Error in f5_obj$ls(recursive = FALSE) : HDF5-API Errors:
error #000: ../../../src/H5L.c in H5Literate(): line 1138: link iteration failed
class: HDF5
major: Links
minor: Iteration failed

error #001: ../../../src/H5L.c in H5L__iterate(): line 3440: link iteration failed
class: HDF5
major: Links
minor: Iteration failed

error #002: ../../../src/H5Gint.c in H5G_iterate(): line 893: error iterating over links
class: HDF5
major: Symbol table
minor: Iteration failed

error #003: ../../../src/H5Gobj.c in H5G__obj_iterate(): line 683: can't iterate over dense links
class: HDF5
major: Symbol table
minor: Iteration failed

error #004: ../../../src/H5Gdense.c in H5G__dense_iterate(): line 1041: link iteration failed
class: HDF5
major: Symbol table
minor: Iteration failed

error #005: ../../../src/H5B2.c in H5B2_iterate(): line 444: node iteration failed
class: HDF5
maj
```

**Comment by adnaniazi** [comment]
Hi, 

Thank you for using tailfindr. 

Can you send me a FAST5 file so that I can debug it.

Adnan

**Comment by MustafaElshani** [comment]
Hi Adnan

Thank for your reply and help attaches is a Fast5 files

Please do let me know if you manage to receive it

Mustafa
 PAK50842_pass_barcode42_e190dcfc_9.fast5
<https://drive.google.com/file/d/1W-Vqp_AsMjxcUdWzHM8g2h8fmD-kjp5O/view?usp=drive_web>

**Comment by adnaniazi** [comment]
Hi,

I have been able to run tailfindr at my end without encountering the HDF5-API Errors. So there is some problem with the HDF5 library on your system. Please make sure the you have correctly installed HDF library and the VBZ plugin. Try running tailfindr on tailfindr's internal data first and then run it on your data.

tailfindr could not find any tail in your data though. What protocol did you use to create this data? Is it a custom protocol?  tailfindr cDNA alogrithm is currently tunned for the adapter sequences that the SQK-PCS111 kit uses.

Best,
Adnan

**Comment by MustafaElshani** [comment]
Hi Adnan

I will re-check the HDF libraries, I have gone through the process of
install HDF and VBZ but will go through it again

As for the data this was samples I sent to an external company to sequence
(big-mistake) so I'm trying to figure exactly what they have done

The samples were re-basecalled using following

Basecalling (guppy version v6.0.6) ✔



guppy_basecaller --config dna_r9.4.1_450bps_sup_prom.cfg \

--input_path raw_data/ \

-r \

--save_path basecalled/ \

--barcode_kits EXP-PBC096 \

--device cuda:0 \

--min_qscore 7 \

--fast5_out \

--calib_detect \

--chunk_size 10245 \

--chunks_per_runner 512 \

--num_callers 4 \

--gpu_runners_per_device 12 \

--trim_strategy none


Thanks for your help
Mustafa

**Comment by nemitheasura** [comment]
@MustafaElshani , @adnaniazi ,

I had the same issue working with nanopore data on Windows11. While using test data provided with tailfindr - everything worked, while using my own data (guppy 6.0 was used) the output was blank. 

After many tries and errors, I found a solution. Might not be the most elegant way, but it works. 

I installed the patched R version from this link: https://cran.r-project.org/bin/windows/base/rpatched.html
and compatible Rtools from this link: https://cran.r-project.org/bin/windows/Rtools/rtools42/files/rtools42-5253-5107-signed.exe
Then installed devtools via install.packages() and rhdf5 from Bioconductor: https://bioconductor.org/packages/release/bioc/html/rhdf5.html
However, the session_info() showed that there is an issue with rhdf5filters (md5sum), so I installed this directly from github using devtools (from there: https://github.com/grimbough/rhdf5filters)
After that I went to the ont-vbz plugin directory, copied the plugin and lib files and pasted them to the lib directory within the rhdf5filters directory (in my case it was C:\Users\nemitheasura\AppData\Local\R\win-library\4.2\rhdf5filters\lib\x64).

After those steps I installed tailfindr from the repo and ran the pipeline on my data. 
The problem was solved, the csv file was not empty. 

Best,
N.
