### ISSUE TITLE
Rebasecalled not having event table?

### ISSUE THREAD

**Issue by cnk113** [adnaniazi/tailfindr#4]
Hello,

I'm having trouble with my fast5 for input saying they were live basecalled. I rebasecalled them with but it still throws an error. I would like to attach a fast5 file, but it's 33Mb compressed so it's too big to be uploaded.
This is my basecaller command: `guppy_basecaller --flowcell FLO-MIN106 --kit SQK-LSK109 --device cuda:0 -i fast5_pass -s gpu_pass --gpu_runners_per_device 24 --fast5_out --hp_correct 1 --recursive`
When I do h5ls this is what I get:
`/read_00035a7e-319e-47f4-94ca-2e82222b482f Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000 Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/BaseCalled_template/Move Dataset {3263}
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/BaseCalled_template/Trace Dataset {3263, 8}
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/Summary Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Segmentation_000 Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Segmentation_000/Summary Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Analyses/Segmentation_000/Summary/segmentation Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Raw Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/Raw/Signal Dataset {7057/Inf}
/read_00035a7e-319e-47f4-94ca-2e82222b482f/channel_id Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/context_tags Group
/read_00035a7e-319e-47f4-94ca-2e82222b482f/tracking_id Group`
Any ideas?

**Comment by adnaniazi** [comment]
Hello Chang, Thank you for using tailfindr. Can you please upload the file to Dropbox/Google Drive and send me the link to it. I need the file to be able to troubleshoot the issue. Thanks. You can email me on adnaniazi@gmail.com.

**Comment by cnk113** [comment]
Hey Adnan,

Thanks for all the help.
I've attached the gzipped fast5 file.

Best,
Chang

 recovered_b91b7ea4-0e31-48df-b948-995556f17a9a_...
<https://drive.google.com/file/d/1iP6iN0cP0ohV8U1BuGy8E2yOvLY7efSD/view?usp=drive_web>

**Comment by adnaniazi** [comment]
I was able to run tailfindr successfully on the FAST5 that you sent me. Please see the attached CSV file as PDF. Command I used was:
df <- find_tails(fast5_dir = "~/Downloads/untitled_folder", save_dir = "~/Downloads/untitled_folder", csv_filename = 'tail.csv')

You can uninstall tailfindr, and install it again from Github, and then run tailfindr again. Hopefully it will run. Please note that tailfindr looks for primer sequences to identify cDNA reads as poly(A) tail-containing read and poly(T) tail-containing reads in the find-dna-tailtype.R file. https://github.com/adnaniazi/tailfindr/blob/master/R/find-dna-tailtype.R
Line 118         fp <- Biostrings::DNAString('TTTCTGTTGGTGCTGATATTGCTGCCATTACGGCCGGG')
Line 119        ep <- Biostrings::DNAString('ACTTGCCTGTCGCTCTATCTTC')

fp stands for front primer sequence, and ep stands for end primer sequence. 

All your reads were classified as invalid probably because may be you used different primer sequences than the ones tailfindr is looking for. If this is the case, you should fork tailfindr, modify the fp and ep sequences in the find-dna-tailtype.R file, and the install tailfindr from the forked (modified) version.

Feel free to ask if you have any problems with tailfindr in future.

[tail.pdf](https://github.com/adnaniazi/tailfindr/files/3613566/tail.pdf)
