### ISSUE TITLE
Error while processing fast5

### ISSUE THREAD

**Issue by teenu** [adnaniazi/tailfindr#6]
● Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
Error in explore_basecaller_and_fast5type(fast5_files_list[1], basecall_group = basecall_group) : 
  object 'model' not found

**Comment by adnaniazi** [comment]
Most probably your FAST5 files were live base-called using MinKNOW. Those files do not have the Event/Move table. The solution is to re-basecall your FAST5 files using standalone Guppy, and then use tailfindr with additional argument: 
`df <- find_tails(fast5_dir='path/to/your/basecalled/fast5/files', save_dir='/any/directory/where/results/should/be/stored', csv_filename = 'tails.csv', basecall_group = 'Basecall_1D_001', )`

**Comment by teenu** [comment]
The FAST5 files were not live base-called with MinKnow. I'm sorry but I don't understand 're-basecall' using Guppy. Do you mean basecalling and generating fastq ?

**Comment by adnaniazi** [comment]
Can you send me a few of the FAST5 files that you are using as input to tailfindr. I will have a look and then let you know what the problem is. You can email them to me on adnaniazi@gmail.com

**Comment by teenu** [comment]
Sure !

**Comment by adnaniazi** [comment]
I had a look into the FAST5 file that you sent me. This file is raw; it has not been basecalled yet. First, you have to basecall your raw FAST5 files using a basecaller, such as Guppy. Do not forget to use `--fast5_out` option during basecalling with Guppy. This will ensure that both FASTQ and FAST5 files are produced after basecalling. I think you hadn't used `--fast5_out` option, so that is why you only got FASTQ as output from the basecaller. So the solution is do basecalling of the raw FAST5 file again, but this time with `--fast5_out` option. Once you have the basecalled FAST5 files with you, then use tailfindr like this:
`df <- find_tails(fast5_dir='path/to/your/basecalled/fast5/files', save_dir='/any/directory/where/results/should/be/stored', csv_filename = 'tails.csv')`

**Comment by teenu** [comment]
That resolved the issue. Thanks !

**Comment by manburst** [comment]
Hello, I have re-basecalling with guppy option `--fast5_out` but the output still said that I basecalled with minknown. Could you look at my fast5 file, please?
My fast5 files in multi-fast5 are that a problem?
Here code (I replaced example file with my file)
`library(tailfindr)
library(rbokeh)
library(hdf5r)
library(rhdf5)
library(Rhdf5lib)
df <- find_tails(fast5_dir = system.file('extdata', 'rna', package = 'tailfindr'),
                 save_dir = '~/Downloads',
                 csv_filename = 'tails.csv',
                 num_cores = 2,
                 save_plots = TRUE,
                 plot_debug_traces = TRUE,
                 plotting_library = 'rbokeh')`

**Comment by adnaniazi** [comment]
Try using an additional argument in the above command:
basecall_group='Basecall_1D_001'
and see if it works. 

If it does not then send me your multifast5 file.
