### ISSUE TITLE
DNA kits

### ISSUE THREAD

**Issue by dweemx** [adnaniazi/tailfindr#66]
Hi @adnaniazi,

Thank you for the useful tool!

I was wondering whether you think `tailfindr` could work to estimate the length of the poly(A) region when using the SQK-NBD114-96 (FLO-MIN114) by adapting the `front_primer` and `end_primer` ? The primer sequences that I would use are the ones available at [here](https://community.nanoporetech.com/technical_documents/chemistry-technical-document/v/chtd_500_v1_revan_07jul2016/adapter-sequences).

**Comment by adnaniazi** [comment]
Hi, Sorry for the late reply. I no longer maintain tailfindr. Dorado from ONT can now do polyA-tail estimation on both RNA and cDNA now. So I would encourage you to use it instead of tailfindr. You can however try to change the front_primer and end_primer in tailfindr, and see if that works for you.
Best,
Adnan

**Comment by dweemx** [comment]
Hi @adnaniazi,
Thank your reply!
Yes indeed, however they currently do not support poly(A) estimation for DNA
