### ISSUE TITLE
Position tail in basecalled sequence

### ISSUE THREAD

**Issue by grexor** [adnaniazi/tailfindr#7]
Hi Adnan, great software, congrats!

Quick question: tail_start and tail_end numbers are in coordinates of the "samples" (signal/raw data), is there a way to report it in terms of the basecalled read?

Or more generally (i know this is not a tailfindr topic): do you know of a tool that can show the mapping of raw signal (squiggle, samples data) to the basecalled sequence in the fast5 file?

I am learning of the "move" and "trace" data in fast5 but i don't know how to convert these into the mapping described above,

Thanks,
Gregor

**Comment by adnaniazi** [comment]
Hi Gregor,

Thank you for using tailfindr. 

About your first question: Do you want the basecalled sequence which was predicted by the basecaller between tail_start and tail_end boundaries estimated by the tailfindr? If yes, then I can modify tailfindr for you to output this information. Just knowing which base was predicted at tail_start location, and which base was predicted at tail_end location isn't very informative -- in my opinion. In most cases, it would be A for both these sites. I think the sequence between these two boundaries would be most useful for you.

About your second question: tailfindr has the code already that assigns samples to the basecalled reads. It is just not exported, so it can't be used by the users. I can make for you a simple function tomorrow that can do this mapping for you -- if you want. Are you using Guppy or Albacore for basecalling, and are your files single fast5 or multifast5?

Adnan

**Comment by grexor** [comment]
Hi Adnan,

thanks for the super fast reply. Basically my idea is very simple: i would just like to see "where" is the detected tail relative to the basecalled read. I use guppy to basecall, and i was informed that the caller doesn't include the polyA tail in the reported read sequence, since it can't basecall long uniform stretches (or something in this direction).

So for me it would be important to see, somehow, where is the identified tail compared to the basecalled read. This could be In terms of samples (raw_signal), or in terms of nucleotides (don't know if this is possible?). So something in this direction, does it make sense?

Additionally, you mention it would be possible to get the actual tail sequence between tail_start and tail_end. This would also be very useful, however is this basecalled by guppy for example but simply not reported? Or you would basecall it with tailfindr?

Your suggestion to be able to report the assigned samples to the basecalled reads seems the right way for me, it would be super if you could add a function to report that. I use guppy and fast5,

Thanks for all the help and fantastic work!,
Gregor

**Comment by adnaniazi** [comment]
Guppy basecalls the entire read -- transcript and the poly(A) tail -- but not the adaptor at the 3 prime end. Older versions of guppy used to output a single A for the entire duration of the poly(A) tail. The recent versions of Guppy, however, have gotten a lot better at calling shorter poly(A) tails. So if you have a 10 nucleotide long poly(A) tail, then chances are that you would actually see a sequence of 10 A's in your FASTQ file (sometimes guppy will output only one A for these 10nt poly(A) tails, but such cases are rare). But when it comes to longer poly(A) tails, Guppy fails to output the right amount of A's all the time. So if the poly(A) tail is, lets say, 100 nt long, Guppy will only predict 25 As in the poly(A) region instead of 100. In summary, long poly(A) tails (>30nt) are underestimated all the time by Guppy, and short poly(A) tails (<30) are estimated fairly accurately most of the time, and you should be able to see a stretch of A's in your FASTQ files.

Because the output of the Guppy is not accurate 100% of the time, therefore, you need tools like tailfindr, or Nanopolish, or Poreplex to give you the correct estimate of length of the poly(A) tail.

tailfindr does not do basecalling. However, the information that you need such as when (in terms of sample #) and what base was predicted by Guppy, this information can be extracted from the Move table and some other information present in the basecalled file. 

1. I will create a branch of tailfindr for you that will output the index of the bases at the boundaries of the poly(A) tail.

Lets say that tail_start is 100 (in sample #) and tail_end is 1100 (in sample #), and the tail length predicted by tailfindr is 60 nt. I will add two additional columns to the CSV output of tailfindr tail_start_base_index, and tail_end_base_index.

In our example, tail_start_base_index will lets say corresponds to base # 10 in the FASTQ, and tail_start_base_index will correspond to the base # 20 in the FASTQ sequence (see the FASTQ sequence below). 

FASTQ is:
ATCGATCGAT AAAAAAAAAA GCGCGTCGATCGATGGCGT

So now with these two additional columns of information, you will know at what base the tail started and at what base it end, and how many bases were predicted by Guppy in between these two ends, and how many bases were predicted by tailfindr.

Is that what you want?

2. I will create a simple function for you which will tell you where in samples, Guppy predicted a new bases and which base was it.

**Comment by grexor** [comment]
Thanks Adnan, yes that would be fantastic!

So if i understand you correctly: guppy uses the entire raw_signal and calls all bases, but in case of long polyA stretches, it sometimes underestimates this and puts a single A, or sometimes more, and especially for very long tails it underestimates.

Another question: looking at some public data and a specific read, guppy basecalled sequence was 326 nt long (the sequence doesn't contain any polyA stretches, just two AA), and the predicted tail from tailfindR is 412.24 (tail_length). Does this mean that guppy simply put a single A (or AA)?. Would your modified tailfindR then report tail_start_base_index as the last base+1 of the guppy called sequence and tail_stop_base_index further downstream (if the polyA tail was at the 3'-end)?

Sorry for all the trouble, just trying to understand things here :)

Thanks,
Gregor

**Comment by adnaniazi** [comment]
You understand it correctly now.

For your question:
Yes, guppy predicted just two A's for a poly(A) tail that tailfindr predicts to be 412 A long. 

You must know that every sample in the raw single has a corresponding base prediction. The move table in FAST5 file defines at what time point (sample #6 ) there is a transition in the base prediction. So I will just give you the index of the FASTQ bases at the two boundaries of the poly(A) tail.

Please see the attached image, and let me know if you get what I mean.



![WhatsApp Image 2019-10-29 at 12 49 28 PM](https://user-images.githubusercontent.com/6848063/67764647-b56f3980-fa4a-11e9-904a-a075ec67f575.jpeg)

**Comment by grexor** [comment]
Super, one more thing: in your example, the tail is basecalled by guppy with: ACA ? (since the tail starts with A, but then there is a C in the middle, and ends with A). I see, i think guppy basecalls the C because there is a change in signal in the middle, but tailfindR says its just one tail all together (long stretch of constant signal). An idea: wonder if it would be possible to report the tail in this more detailed way, like 10A + C + 10A, or something. The error rate is high, however it would be interesting to see which other nucleotides other than A (and where) are detected in the tail. Thanks, Gregor

**Comment by adnaniazi** [comment]
Yes, sometimes there are dramatic singal changes within the poly(A) tail which are then detected as a new base. tailfindr, is robust against these transitory spikes in the poly(A) region. I can output the full sequence between the two final ends of the polyA tail, so the output in the case of the attached picture would be ACA. But an output like 10A + C + 10A would require a complete rework of the algorithm because I would need to find the length of each of the fragments of the polyA tail separately. I am afraid I don't have time for that at present.

Can you email me a about 5 of your RNA basecalls reads. My email is adnaniazi@gmail.com. Thanks. I will check the modified tailfindr on these reads.

**Comment by grexor** [comment]
Thanks Adnan, e-mailed! Yes of course, these are all just ideas, if you update tailfindR in the future with this extended "tail" report please ping it somewhere; i know there are people working on the nucleotide changes in the polyA tail and would perhaps be super interested in that, Cheers, Gregor

**Comment by adnaniazi** [comment]
Great. Thanks! I agree with you. I will keep you posted on it when I manage do it.

In the meantime, I have a new tailfindr branch for you. It is now ready. You can install it by:
devtools::install_github("adnaniazi/tailfindr", ref ="gregor_polya_base_end").

It will fail on one of the five reads that you sent me, but that's because that particular read has no clear poly(A) tail like region in it.

These are the additional columns that will now be added to the output dataframe/CSV:
tail_start_base_index = Index of the fastQ base corresponding to the tail start site
tail_end_base_index =   Index of the fastQ base corresponding to the tail end site
polya_tail_fasta_seq =5 prime to 3 prime sequence in the poly(A) tail region as predicted by the Guppy
full_read_fasta_seq = 5 prime to 3 prime fasta sequence for the entire read.

I will send you the function for mapping signal to basecalls momentarily.

**Comment by adnaniazi** [comment]
You can use the following function to create a mapping between samples in the signal and the Guppy basecalls.
https://gist.github.com/adnaniazi/8e80e9538be495afdfbe269ce25a05e3

Just give this function the path of a fast5 file like this:

`df <- extract_read_data(file_path = "/Users/adnaniazi/Downloads/_check/Porecamps_MacBook_Pro_local_20171009_FAH20409_MN17024_mux_scan_Bham_Run1_20171009_DirectRNA_60268_read_100_ch_21_strand.fast5")
`

and it will return a dataframe containing all the read information, some of which you won't need.

```
raw_signal <- df$raw_data
event_data <- df$event_data
```

`raw_signal` will contain an array of sample values.
event `data` will contain a matrix of mapping information between signal and basecalls. Here is snapshot of it:
![https://i.ibb.co/Z1XHHcC/Screen-Shot-2019-10-29-at-3-14-04-PM.png](https://i.ibb.co/Z1XHHcC/Screen-Shot-2019-10-29-at-3-14-04-PM.png)

The `model_state` column shows you the base predicted by Guppy for samples starting from `start` index in `raw_signal`. The `move` column tells you whether the base that you are seeing in the `model_state` column is a new base (`move = 1`) or the previous base (`move = 0`). Move=0 means that no new base has been detected at these samples because the previously-predicted base is still persisting.

Hope this helps!

**Comment by grexor** [comment]
That's fantastic Adnan, works :-)

Just to double check, i just realized (can you please confirm?) that the raw_signal data in direct-RNA Nanopore is from 3'->5' (sample# 0,1,2...), and the guppy basecalled sequence (stored in fast5 and fastq files) is reported in 5'->3' (not reverse-complemented, just the base sequence is read from the end to beginning). That's why you also draw your diagram 3'->5'?

I read it in this paper (https://www.nature.com/articles/s41467-019-08734-9):

> Each nanopore-derived sequence read represents a single full length or 5′ truncated transcript, read in the 3′ – > 5′ direction

Thanks again, Gregor

**Comment by grexor** [comment]
I guess my question is, i have this read which is 326 nt long, and the tail is 412.24 (tailfindr), the tail is reported by guppy as a single A. And the new indices of the tail in the read are 1-1, so the first A of the basecalled sequence represents the tail. In this case the tail is at the beginning of the read? (at the 5' end)? Thanks, Gregor

**Comment by adnaniazi** [comment]
Yes you are right. The sequencing, and hence, the raw signal goes from 3 to 5 prime. Event, move and trace tables are all 3 to 5 prime, going from top to bottom. The basecalled sequence is reversed before it is saved by Guppy, so the fastq sequence is always 5 to 3 prime. And hence the weird numbering in my hand drawn picture.

I looked at the read that you are referring to. This seems like a wierd chimeric read with following arrangement: transcript - adaptor -    poly a tail at the end. A Nomal read is : adaptor-polya tail- transcript.

**Comment by grexor** [comment]
Thanks Adnan, i also double checked meanwhile with your extract_read_data function and saw that in fact it's exactly how i assumed and you described. All the best, Gregor
