### ISSUE TITLE
R session aborted

### ISSUE THREAD

**Issue by robinycfang** [adnaniazi/tailfindr#8]
Hello there,

I have been using tailfindr on my ONT direct RNAseq data. It worked well on the smaller data (\~50Gb fast5), but when I worked with larger datasets (>80Gb), R studio just somehow crashed (R session aborted) at the last step (writing results to the csv I think). I think my computer has 48 CPUs, and I used 20\~30 CPUs.

Thanks!

**Comment by adnaniazi** [comment]
Hi,

Thank you for using tailfindr.  I have seen Rstudio does crashing on large datasets. I would recommend that you make run your Rscript from the terminal using the command "Rscript /path/to/my_tailfindr_script.R". Hopefully this would solve the problem of RStudio crashing because now you won't be using RStudio at all; you will just be using R.

**Comment by robinycfang** [comment]
Thanks! I will try out with the core R and come back with any updates.

YC
